name: Validate Renovate configuration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Validate
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.1.0
        with:
          config_file_path: "default.json"
